apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

replicas:
  - name: demo-deployment
    count: 2

patchesStrategicMerge:
  - |-
    kind: Service
    apiVersion: v1
    metadata:
      name: demo-service
    spec:
      type: NodePort
